
name: Documentation
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Install dependencies
      run: |
        poetry install
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        documentation_path: docs
        install_requirements: "true"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.DOCUMENTATION }}
        branch: gh-pages
