name: CI Pytest
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install -e . --no-cache-dir
        pip install -r requirements.txt
    - name: Run and write pytest
      run: |
        set -o pipefail
        python -m pytest --cov=src --cov-report term-missing | tee pytest-coverage.txt
    - name: Coverage comment
      id: coverage-comment
      uses: MishaKav/pytest-coverage-comment@v1.1.24
      with:
        pytest-coverage-path: ./pytest-coverage.txt
    - name: Output coverage
      run: |
        echo "Coverage Report - ${{ steps.coverage-comment.outputs.coverage }}"
        echo "Coverage Color - ${{ steps.coverage-comment.outputs.color }}"
    - name: Create Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.PYTEST_COVERAGE }}
        gistID: d6c40a5b5a3169c079e8b8f778b8e517
        filename: badge-psycop-ml-utils-pytest-coverage.json
        label: Coverage
        message: ${{ steps.coverage-comment.outputs.coverage }}
        color: ${{ steps.coverage-comment.outputs.color }}
        namedLogo: python
